# Generated by Django 5.1 on 2024-10-21 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_donationarea_donation_gallery_volunteer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.AddField(
            model_name='donation',
            name='documentation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('Books Donation', 'Books Donation'), ('Food Donation', 'Food Donation'), ('Vessel Donation', 'Vessel Donation'), ('other', 'other'), ('Footware Donation', 'Footwear Donation'), ('Furniture Donation', 'Furniture Donation'), ('Cloth Donation', 'Cloth Donation')], max_length=100, null=True),
        ),
    ]
