# Generated by Django 5.1 on 2024-11-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_contact_donor_contact_donation_documentation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donationname',
            field=models.CharField(choices=[('other', 'other'), ('Books Donation', 'Books Donation'), ('Food Donation', 'Food Donation'), ('Footware Donation', 'Footwear Donation'), ('Furniture Donation', 'Furniture Donation'), ('Cloth Donation', 'Cloth Donation'), ('Vessel Donation', 'Vessel Donation')], max_length=100, null=True),
        ),
    ]
